# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["jchampion@fastly.com"]
description = ""
language = "javascript"
manifest_version = 2
name = "javascript"
service_id = "rKKHanY5QNfRmKvkDLKPm3"

[local_server]

  [local_server.backends]

    [local_server.backends.httpbin]
      url = "https://httpbin.org/"

[scripts]
  build = "npm exec js-compute-runtime ./src/index.js ./bin/main.wasm"

[setup]

  [setup.backends]

    [setup.backends.httpbin]
      address = "httpbin.org"
      port = 443
